// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hsnguuozyigpzstwqkrk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhzbmd1dW96eWlncHpzdHdxa3JrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODk4OTU5OTAsImV4cCI6MjEwNTQ3MTk5MH0.W_gzt6ovmXPz36vsroD_MFXjc6vkMjzevYvUtv5yTvs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);